#! /bin/bash

LIBRMN=rmn_015.2
OPTIMIZ="-O 2"
#OPTIMIZ="-O 0 -debug"

. s.ssmuse.dot /ssm/net/hpcs/201402/02/base /ssm/net/hpcs/201402/02/intel13sp1u2
#. s.ssmuse.dot /ssm/net/hpcs/201402/02/base /ssm/net/hpcs/ext/xlf_13.1.0.10

. s.ssmuse.dot /ssm/net/cmdn/vgrid/5.4.0/${COMP_ARCH}
. s.ssmuse.dot /ssm/net/rpn/libs/15.2
. s.ssmuse.dot /ssm/net/rpn/libs/ezinterpv/15.2.2-beta

s.compile -o Example_${BASE_ARCH}.Abs -opt ${OPTIMIZ} -libappl descrip ezinterpv -librmn ${LIBRMN} -src Example.ftn90

./Example_${BASE_ARCH}.Abs
